### ISSUE TITLE
💖

### ISSUE THREAD

**Issue by puria** [tidalcycles/strudel#1]
Woke up this morning, I was looking on how vortex was simple... and thought why Qt when I can write the nicest editor ever in js/ts.
Then I init my new project (I am actually experimenting with https://github.com/MylesBorins/node-osc to talk to superdirt) when I saw the notification of this repo ;p coincidences 🥳

**Comment by yaxu** [comment]
Heh nice, did you manage to get some sound out @puria?

**Comment by puria** [comment]
sure as per the hello world, as easy as:

```js
import { Client } from 'node-osc';

const client = new Client('127.0.0.1', 57120);
const msg = ['s', 'cp', 'speed', 2, 'room', 0.5, 'size', 0.8, 'cps', 0.5, 'cycle', 3.3333333333333335, 'delta', 0.333333]

client.send('/dirt/play', msg, () => {
    client.close();
})
```

**Comment by puria** [comment]
I'm also really thinking about some [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar) maybe could be useful also for other languages, although I really don't care about others ;p (maybe you or others do)... but I find it useful for parse the notation from the editor (lookin' at [Peggy](https://peggyjs.org/) ), and send it to SuperDirt... I do really care more about aesthetics and to give more 🤩 to the frontend (to show-off at my techno gatherings)... starting simple... maybe at some point to integrate with other projects like hydra... but for now having my preferred typography family, a nice little wave visual, and the tidal syntax will make me already super happy... kind of feedforward on a web page ;p

**Comment by yaxu** [comment]
Yes there is already a peg for the mini-notation. https://github.com/gibber-cc/tidal.pegjs

**Comment by yaxu** [comment]
That looks nice and easy with the osc. Normally though I would put OSC messages in a bundle with a timestamp a little bit ahead. There might be a little bit of effort to generate the timestamp, which needs to be in ntp format. Hopefully there is an example of this. I can see one on the node-osc npm page but giving a timestamp of '10' which I think wouldn't make sense as that would probably trigger a message some decades in the past :)

**Comment by puria** [comment]
Yeah think that the `ts` management will be the core part of the whole deal... but doable ;p will experiment in the following days and share if think that still is a good idea tomorrow 🤣

**Comment by puria** [comment]
Anyway full of other attempts are there: https://github.com/search?l=JavaScript&q=tidal&type=Repositories some good inspiring ones

**Comment by puria** [comment]
like: https://github.com/njanssen/node-tidal

**Comment by felixroos** [comment]
@puria ahh funny you mention krill, as I just started using krill's peg.js grammar to add mini notation (and a tiny bit of haskell syntax) to [strudel REPL](https://strudel.tidalcycles.org/) (https://github.com/Mdashdotdashn/krill/issues/8). Before, I also [played with tidal.pegjs](https://loophole-letters.vercel.app/tidal-pegjs), but compared to krill, it's rather basic.
Strudel now also has a [discord channel](https://discord.gg/YZgeaTFA), in case you want to participate in some way
