### ISSUE TITLE
Make license clear

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#100]
We should have a copyright notice clear in the source code of https://strudel.tidalcycles.org/ etc, and I think via a statement or link on the page as well.

The GPL also recommends putting a copyright, license and warranty disclaimer notice at the top of every source file. We could do this like:
```
/*
filename.mjs - short description
Copyright (C) 2022  xxx and contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. https://www.gnu.org/licenses/gpl-3.0.en.html
*/
```

The recommended version is a bit longer, but perhaps this is a good compromise.. 

If we make any servers they should probably be under the [Affero GPL](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by felixroos** [comment]
what about the license of music created with strudel, or music that somehow involved strudel in the process of making?

**Comment by yaxu** [comment]
Sorry closed in error!
No the GPL explicitly does not apply to the output of the program.

**Comment by yaxu** [comment]
@felixroos shall we switch to the Affero GPL like hydra? Then as I understand it, the GPL terms apply to any web services we create. I think we should make this choice before accepting any substantial PRs, and check with authors of existing PRs of any change before merging them.

**Comment by yaxu** [comment]
See #101

**Comment by yaxu** [comment]
We're now on AGPL, with file headers added to all .js and .mjs files.

We still need to add a copyright notice to the REPL, and maybe to console.

**Comment by felixroos** [comment]
just noticed that all package.json files still have gpl3 in the license field.

**Comment by yaxu** [comment]
@felixroos ok I'll update them

**Comment by yaxu** [comment]
https://github.com/tidalcycles/strudel/commit/c23f9b862908b2823612a36004d5f26876a074fd

**Comment by yaxu** [comment]
I think this clarifies the license for anyone looking at the minified source and is enough for this ticket:
https://github.com/tidalcycles/strudel/pull/105/commits/b0dfb44e96d30b5d293a101815528713ac09f781

It would be nice to make the license clear to end users as well, but we can do that in a future 'about' page.
