### ISSUE TITLE
Embedding strudel

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#107]
### Discussed in https://github.com/tidalcycles/strudel/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **yaxu** April 29, 2022</sup>
It would be nice to be able to easily add working strudel code to e.g. a discourse forum (like https://club.tidalcycles.org) or wordpress blog via a plugin. Hope no-one minds me capturing some ideas from the discord chat:

* How to make a discourse plugin: https://meta.discourse.org/t/beginners-guide-to-creating-discourse-plugins-part-1-creating-a-basic-plugin/30515
* Iframe example from @felixroos : https://codesandbox.io/s/beautiful-raman-2mxo8b?file=/index.html
  * @felixroos: i could add a flag to the repl url that minimizes the ui for better embedding
  * @mindofmatthew: You don't even need to add a URL param, you can also check `window.location !== window.parent.location`
  * @yaxu: I like the play / reset / open in editor buttons in https://hydra-book.glitch.me/#/
  * @felixroos: it would also be really cool to have a simple web component that uses it's innerText to generate an iframe with strudel + hashed code - `<strudel>cat(...)</strudel>` this would allow embedding the repl in any html file by just adding a script tag
 </div>

- [x] create web component
- [x] adjust style of repl if embedded
- [x] add discourse plugin? or is there an easier way to whitelist web components?

**Comment by felixroos** [comment]
it might be possible to whitelist custom tags: https://meta.discourse.org/t/whitelisting-html-tags-attributes/159653

**Comment by yaxu** [comment]
> it might be possible to whitelist custom tags: https://meta.discourse.org/t/whitelisting-html-tags-attributes/159653

I saw this, the solution points to a line that needs digging out of git history: https://github.com/discourse/discourse-policy/blob/f7a06fb2e0c0aa58e9dc7286d912d52c2a4f6560/assets/javascripts/lib/discourse-markdown/policy.js.es6#L43

I think this solution is to create a discourse plugin that calls:
```
helper.whiteList(['strudel-repl'])
```
I can look into it.

**Comment by yaxu** [comment]
I spent some time on this but didn't manage to whitelist the tag. I've [asked in the discourse forum](https://meta.discourse.org/t/whitelisting-html-tags/225962).

**Comment by felixroos** [comment]
https://github.com/tidalcycles/strudel/pull/109
