### ISSUE TITLE
try loading samples via file system

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#118]
using https://web.dev/file-system-access/ though it's chromium only, it might be really useful. For big sample banks, loading over the network is a trade off between availability and traffic

**Comment by rabidmachine9** [comment]
Just wanted to give a small input here just in case it is not obvious to some people, you can serve your samples via a local server that has CORS enabled. 
The following server is based on python3  https://gist.github.com/rabidmachine9/2e06a5f872d53bdc1c03bb9c12f9df08 you just copy the file inside your "Samples" folder and start the server

`$ cd ~/Music/Samples`
`$ python python3-cors.py 8000`

this will start a local server on port 8000
then you just access your local files like that: https://strudel.tidalcycles.org/#c2FtcGxlcyh7CiAgbHNkOiAnRGlydC1TYW1wbGVzL21ldGFsLzAwMF8wLndhdicsCn0sICdodHRwOi8vbG9jYWxob3N0OjgwMDAvJyk7CnMoImxzZCBsc2QiKQo%3D

Hopefully this helps somebody!

**Comment by felixroos** [comment]
hey thanks for the input! it might make sense to add a chapter to the docs to describe using a local sample server.
It's even possible to do this without needing to create a file and paste code, using something like [serve](https://www.npmjs.com/package/serve), running `npx serve ~/Music/Samples --cors` (requires nodejs). There are probably similar command line servers in the python sphere, which we should probably add for people that don't have node installed..

**Comment by rabidmachine9** [comment]
Yes, this also can happen with and maybe it is nice to find an one liner for the job, the only reason I choose the python server script is because your can choose easier the domains you want to whitelist instead of just whitelisting all domains that the ----cors flag is doing( `response.setHeader('Access-Control-Allow-Origin', '*');` ). 
Whitelisting just a target domain probably makes things a little more secure

**Comment by felixroos** [comment]
I am no security expert but I don't see how a local sample server with lax cors rules could pose a risk, as you can only access the files served in that folder, also only if you have access to localhost

**Comment by bwagner** [comment]
Apparently, the simple [http server](https://docs.python.org/3/library/http.server.html#http-server-cli) in python does not support CORS. But there's an even [shorter script](https://stackoverflow.com/a/21957017/) that worked for me with @rabidmachine9's approach.

**Comment by felixroos** [comment]
this can now be done with https://github.com/tidalcycles/strudel/pull/621 in the desktop app, or using https://github.com/ilesinge/samples4web on the web! The file system access api is chromium only and will probably never land in firefox in the near future, so it's not a great option. The desktop app is more promising to allow doing things that are not or only partly possible on the web
