### ISSUE TITLE
Customisable highlight style?

### ISSUE THREAD

**Issue by gamar3is** [tidalcycles/strudel#1191]
Currently, the highlight style is somewhat hardcoded [here](https://github.com/tidalcycles/strudel/blob/ad080d02b32b35e244a472c104a80a1e54728926/packages/codemirror/highlight.mjs#L117).

Instead of setting a `style` attribute, would it be feasible to set a class instead, so that it can be changed through CSS? 

Ideally this could be then redefined by the user through a function, but just having it as a class would enable me to change things with a userscript and try out other highlighting styles.

**Comment by gamar3is** [comment]
(btw i can try and make a PR for this, just asking to be sure that this feature fits into the project plans)

**Comment by felixroos** [comment]
I think we still need a style attribute to be able to set any color, which isn't possible by a class: https://strudel.cc/#cygiYmQqPDEgMj4gLSwgaGgoMTAsMTYpLC0gcmltIikuYmFuaygnQ2FzaW9SWjEnKQouY29sb3IoIltjeWFuIHwgbWFnZW50YSB8wqB5ZWxsb3ddKjgiKQouX3BpYW5vcm9sbCgp

**Comment by gamar3is** [comment]
Oh I see -- this is a tricky one. I'd really love to try out different styles for the highlights, e.g. with CSS transitions, so I'll keep thinking of a possible approach that doesn't break the `color()` feature.

Right now I'm thinking that adding a class (e.g. `highlight-char`) in addition to the style attribute would allow for this. The style attribute would likely override any CSS styles for the class, but maybe `!important` would address this.

I'll try to find some time during the weekend to set up a dev environment and test this out, but I'd definitely welcome any caveats you see with this approach.

Thank you for the quick reaction! I'm porting my work from Tidal to Strudel mostly because of the highlight feature, so I'm really eager to help make things even better.

**Comment by gamar3is** [comment]
I actually got this going -- adding the `highlight-char` class in `packages/codemirror/highlight.mjs` then editing the style in `website/src/styles/index.css` works. I'm delighted at how easy it is to hack on Strudel.

Now wondering if it makes sense to have a user-facing function to alter the highlight style. I'll read up on how Strudel does things like `.color()` and hopefully come up with something.

**Comment by matthewkaney** [comment]
One thought: perhaps Strudel could have a `css` (or `highlightCSS`) param that could override the color param/default highlighting if set?

**Comment by gamar3is** [comment]
> One thought: perhaps Strudel could have a `css` (or `highlightCSS`) param that could override the color param/default highlighting if set?

I really like this idea, could be finessed later but would make a lot of things possible right now

**Comment by felixroos** [comment]
> One thought: perhaps Strudel could have a `css` (or `highlightCSS`) param that could override the color param/default highlighting if set?

good idea! the rule could be: if `css` is set, `color` is ignored, and `css` is used for the style attribute. maybe also `markstyle` / `markcss`

**Comment by felixroos** [comment]
it should be noted that `color` is also used for the visuals (scope, pianoroll etc). the css wouldn't work for those, as it's canvas based. so I guess the behaviour for the viz would remain unchanged

**Comment by gamar3is** [comment]
> it should be noted that `color` is also used for the visuals (scope, pianoroll etc). the css wouldn't work for those, as it's canvas based. so I guess the behaviour for the viz would remain unchanged

That makes sense, and I can perfectly live with that limitation :-)

**Comment by felixroos** [comment]
<img width="758" alt="image" src="https://github.com/user-attachments/assets/f5a2cdd5-53e2-4b05-9003-ccb5036d4bb9">

**Comment by gamar3is** [comment]
This is *great* and exciting! I suppose we could also call `markcss` autonomously (i mean, outside a chained sound statement) so it affects the whole sketch?

**Comment by felixroos** [comment]
> This is _great_ and exciting! I suppose we could also call `markcss` autonomously (i mean, outside a chained sound statement) so it affects the whole sketch?

you could use `all` for that, like `all(x=>x.markcss('background:tomato'))`

**Comment by felixroos** [comment]
now implemented in https://github.com/tidalcycles/strudel/pull/1202 (soon to be deployed)
