### ISSUE TITLE
Split into separate packages

### ISSUE THREAD

**Issue by charlieroberts** [tidalcycles/strudel#12]
Should these be separate repos? I can imagine other projects (gibber, hydra etc.) wanting to use the library...

**Comment by yaxu** [comment]
What would be the advantage of that, vs having more than one npm package in the same repo?

With Haskell Tidal, the tendency has been to stick everything (tidal, tidal-parse, tidal-listener) in the same repo, but as separate (cabal/hackage) packages, mainly because it makes automated testing easy, as well as making developing closely related libraries at the same time a bit easier.

**Comment by charlieroberts** [comment]
There is no advantage. I've never seen this done with npm, so I didn't know it was possible, but a cursory web search suggests it can be done... I'll be curious to see how it works, as it would be a much better model for gibber as well.

**Comment by puria** [comment]
suggest a monorepo for the better ;p

**Comment by charlieroberts** [comment]
for reference: https://dev.to/limal/simplify-your-monorepo-with-npm-7-workspaces-5gmj

**Comment by felixroos** [comment]
yup, I would also suggest a monorepo, as it's much easier for multiple packages. This is quite a standard practise in the industry. There's also a tool called [lerna](https://lerna.js.org/), which simplifies that. The question is of course how we should split the packages. I would suggest going after dependencies:

- `@strudel/core` -> core logic. currently `strudel.mjs`. zero dependencies
- `@strudel/scheduler` -> scheduler logic. currently `useCycle.ts` with react hook + tone. tbd: encapsulate
- `@strudel/mini` -> mini notation parser. currently `parse.ts`. contains krill parser
- `@strudel/eval` -> user code shifter and evaluator. currently `evaluate.ts`. depends on `shift` packages
- `@strudel/repl` -> repl react hooks (`useRepl.ts`, `useCycle.ts`) + components (`App` = Repl +  `MiniRepl`)
- `@strudel/tone` -> `tone.ts` depends on tonejs
- `@strudel/tonal` -> `tonal.ts` + `voicings.ts` depends on @tonaljs and `chord-voicings`
- `@strudel/midi` -> midi.ts. depends on `webmidi`
- `@strudel/tunes` -> collection of user tunes? could also be part of repl
- what else?

Most of these packages are already encapsulated, this should mostly be a matter of copy and paste. 
Only `scheduler` has to be encapsulated from react and possibly tone. Maybe we can also integrate the scheduler into core.

With that structure, strudel will be flexible and cheap to integrate into other projects. 
Also, it would be easy for people to add functionality without blowing up existing packages.

What do you think?

**Comment by yaxu** [comment]
This looks well thought through to me, thanks. No strong feelings, but if the scheduler has no dependencies, perhaps it's easiest to put it in core.

**Comment by puria** [comment]
Pardon me, not participating on development of strudel yet (although love at some point) but... since no hard feeling and starting from scratch, I would suggest to consider https://turborepo.org/ rather than lerna for simplicity and speed in dev time ;p (had previous experience with both).

**Comment by charlieroberts** [comment]
If it helps in terms of deciding what goes in core, I will only pull in strudel.mjs, but acknowledge that my use case might be different from most.

**Comment by charlieroberts** [comment]
Possibly a related issue... what packages should the top-level `package.json` require? Right now I can't build strudel despite trying to install all the missing dependencies, it'd be great to have a working install / run process in place.

**Comment by felixroos** [comment]
packaging complete, see https://github.com/tidalcycles/strudel/pull/24

**Comment by felixroos** [comment]
The packages are now released! See https://www.npmjs.com/org/strudel.cycles . I created short usage examples + code sandboxes for most of the packages. Now everybody should be able to hack on tidal patterns in the browser 🎉  The API still has some rough edges, but it'll smooth out in future versions.
