### ISSUE TITLE
When I hit Ctrl+Enter, it evaluates but also inserts a new line in the editor (same as pressing Enter) (Chrome, Linux, Ubuntu)

### ISSUE THREAD

**Issue by munshkr** [tidalcycles/strudel#122]
* Browser: Google Chrome 101.0.4951.64
* OS: Ubuntu

**Comment by munshkr** [comment]
Thanks!

**Comment by felixroos** [comment]
thanks for reporting! just had to add another little fix for async patterns, now it should work in all cases
