### ISSUE TITLE
Support zero width queries

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#149]
`"a b".queryArc(0,0)` will return nothing, rather than the first event as with tidal

**Comment by felixroos** [comment]
An easy fix would be to check if begin and end are the same, then just query begin+some small number to get the first hap(s). Probably not the cleanest approach though

**Comment by yaxu** [comment]
This is something that works well in tidal, but not in the current 'cycseq' dev branch, which is based on the same innards rewrite as strudel... Fixing this on https://github.com/tidalcycles/strudel/tree/fix-zero-length-queries
