### ISSUE TITLE
early and late behave the same

### ISSUE THREAD

**Issue by giohappy** [tidalcycles/strudel#170]
And it looks like early is not doing what it's supposed to do:

https://strudel.tidalcycles.org/#c3RhY2soCiAgc2VxKGU1LCBlNCwgYjQuZWFybHkoMC41KSksCiAgc2VxKGU1LCBlNCwgZzQubGF0ZSgwLjUpKQop

**Comment by yaxu** [comment]
That is working as I expect. If you making something happen half a cycle earlier, that's the same as making it happen half a cycle later. How do you think it should behave?

**Comment by giohappy** [comment]
@yaxu ok probably I have a wrong understanding of cycles within a sequence. I expected the hear b4 sound earlier, i..e. overlap with the previous cycle. The cycle concept is instead "modular", so earlier is the same as later. Is it right?

**Comment by yaxu** [comment]
Ah I think the confusion is that `g4` is its own pattern, repeating once per cycle, forever. So `g4.late(1)` is identical to `g4` and `g4.late(0.5)` is identical to `g4.late(-0.5)`.

`seq` combines those three patterns by squishing them into a cycle, so they each get a third of a cycle. But they can't 'bleed' into them like you were expecting.

You could do this though:
https://strudel.tidalcycles.org/#c3RhY2soCiAgc3RhY2soImU1IH4gfiIsICJ%2BIGU0IH4iLCAifiB%2BIGI0Ii5lYXJseSgxLzYpKSwKICBzdGFjaygiZTUgfiB%2BIiwgIn4gZTQgfiIsICJ%2BIH4gYjQiLmxhdGUoMS82KSksCik%3D

**Comment by giohappy** [comment]
thx @yaxu for the clarification.
My solutions was a bit more convoluted, since I want to keep the second note playing:

https://strudel.tidalcycles.org/#c3RhY2soCiAgdGltZUNhdChbMSxlNV0sIFsyLHN0YWNrKGU0LGI0LmxhdGUoMS80KSldKSwKICB0aW1lQ2F0KFsxLGU1XSwgWzIsc3RhY2soZTQsYjQubGF0ZSgzLzQpKV0pCik%3D

**Comment by yaxu** [comment]
You can also extend over two steps in the mininotation like this: https://strudel.tidalcycles.org/#c3RhY2soCiAgc3RhY2soImU1IGU0QDIiLCAifiB%2BIGI0Ii5lYXJseSgxLzYpKSwKICBzdGFjaygiZTUgZTRAMiIsICJ%2BIH4gYjQiLmxhdGUoMS82KSksCik%3D

**Comment by giohappy** [comment]
Sorry for abusing your availability @yaxu.  Is there a way to simulate the `left` and `right` structure operators? I guess the add, sub, mul and div modifiers work as `both` in Tidal, right?

**Comment by yaxu** [comment]
add is an alias for addIn, which is the same as the left operators in tidal. There's also addOut and addMix rather than right/both.
There's some info here https://github.com/tidalcycles/strudel/pull/88
