### ISSUE TITLE
Can't run REPL from main branch, get a vite error

### ISSUE THREAD

**Issue by debrisapron** [tidalcycles/strudel#180]
On a fresh clone of main, `npm run setup` followed by `npm run repl` isn't working. The server starts up fine, but as soon as I hit localhost:3000 I get the following error:

```
8:51:40 AM [vite] error while updating dependencies:
Error: ENOENT: no such file or directory, open '/Volumes/dbd/repos/debrisapron/strudel/node_modules/@codemirror/highlight/dist/index.js'
```

On macOS 10.14.6, node 18.7.0.

**Comment by felixroos** [comment]
can you try `npm i @codemirror/highlight`?

**Comment by debrisapron** [comment]
Sorry I should have said, I already tried that (from the root). However you bringing it up made me think I should try installing it in `/repl` instead and that fixed it. Duh. Closing.
