### ISSUE TITLE
Something's wrong with squeezeJoin (was: silence when using slow before chop)

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#216]
when slowing down a pattern before calling .chop , the pattern will return nothing:

```js
let p = s("hh").chop(4) // this works
let p = s("hh").chop(4).slow(2) // this also works
let p = s("hh").slow(2).chop(4) // this doesnt work
```

[repl link](https://strudel.tidalcycles.org/?70M98P_ZVSJe)

Could this be a bug in `_squeezeJoin` ? I am not entirely sure what the expected result should be, probably the same as line 2.

**Comment by felixroos** [comment]
same with ply, which also uses squeezeJoin: https://strudel.tidalcycles.org?SB-hFm0uROHV

**Comment by yaxu** [comment]
```js
s("hh").slow(0.5).chop(4)
```
is ok..

In tidal `chop 4 $ slow 2 $ s("hh")` seems OK but `ply 4 $ slow 2 $ s("hh")` is not.

In tidal `ply` is implemented using a `squeezeJoin` and `chop` isn't.. Which backs up your theory that there's something up with `squeezeJoin`.

**Comment by yaxu** [comment]
This does work in tidal:
```hs
*Sound.Tidal.Context> ply 2 $ slow 2 $ s "bd sd"
(0>½)|s: "bd"
(½>1)|s: "bd"
```
this doesn't
```hs
*Sound.Tidal.Context> ply 2 $ slow 4 $ s "bd sd"
```

**Comment by yaxu** [comment]
Doesn't work in tidal 2.0 either..
```hs
*Sound.Tidal.Signal.Base> _ply 2 $ _slow 4 $ fastcat [sigAtom "hh" :: Signal String, sigAtom "bd"]
[]
```

**Comment by yaxu** [comment]
I think the problem starts here:
```js
  _compress(b, e) {
    if (b.gt(e) || b.gt(1) || e.gt(1) || b.lt(0) || e.lt(0)) {
      return silence;
    }
    return this._fastGap(Fraction(1).div(e.sub(b)))._late(b);
  }
```
`squeezeJoin` is trying to get `_compress` to _expand_ a pattern into a hap larger than a cycle, and it's refusing..

**Comment by yaxu** [comment]
Getting somewhere, not quite there yet though..

**Comment by yaxu** [comment]
Ok this returns 0.5 and not 3.5, so there's definitely something wrong with squeezeJoin.. So something makes sense now.
```js
pure(time.struct(true))._squeezeJoin().queryArc(3,4)
```

**Comment by yaxu** [comment]
Now I understand - the inner pattern of `ply` is just the original value wrapped in `pure`, repeating forever. So, it doesn't matter that you always get the first cycle of that. All the cycles are the same. The progression of time comes from the _outer_ pattern.. But `squeezeJoin` still needs fixing for other cases like the above, where the inner pattern isn't the same every cycle.
