### ISSUE TITLE
updating vitest fails randomness tests

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#245]
updating from  0.21.1 to 0.24.5 changes the results of the randomness tests. it seems that one of both versions does not reset its state or something. eventually related with https://github.com/vitest-dev/vitest/pull/1754 but not really sure. 

it seems that the newer version does not behave like the repl would, e.g. http://strudel.tidalcycles.org/#c3RhY2soCiAgICBzKCJiZCA8c2QgY3A%2BIikKICAgIC5kZWxheSgiPDAgLjU%2BIikKICAgIC5kZWxheXRpbWUoIi4xNiB8IC4zMyIpCiAgICAuZGVsYXlmZWVkYmFjaygiLjYgfCAuOCIpCiAgKS5zb21ldGltZXMoeD0%2BeC5zcGVlZCgiLTEiKSkK always starts with .8 delayfeedback so does the current test. with the new vitest version, it starts with .6 ..

tried various combinations of `--no-isolate` and `--no-threads` flags, but no luck so far.

**Comment by yaxu** [comment]
Hmm so is randomness not a deterministic pure function of time in strudel?

**Comment by felixroos** [comment]
yes it is, but between different versions of the test runner, the determinism seems to have switched how it always behaves :)

**Comment by yaxu** [comment]
heh strange !

**Comment by felixroos** [comment]
the problem should be that the mini notation "|" alignment as well as "?" operator use a stateful randomness, which behaves differently when multiple patterns are queried one after the other. see https://github.com/tidalcycles/strudel/commit/306004ecd2a98a9ac2e289e7f43265f7d44c9213 i don't remember what the seed approach originally tried to solve, maybe @bpow still knows?

**Comment by felixroos** [comment]
> i don't remember what the seed approach originally tried to solve, maybe @bpow still knows?

probably this: https://github.com/tidalcycles/strudel/pull/165#issuecomment-1200476739
