### ISSUE TITLE
Patterns as numbers

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#262]
There's times where it would be convenient to be able to do this:
```js
name("thing").a(3).b(2).c(1.5).mul(2)
```
.. where the values that are numbers (i.e. where `typeof value === 'number'`) in the patterned object get multiplied by 2, making `name("thing").a(6).b(4).c(3)`.

Currently this results in `name("thing").a(6).b(4).c(3).value(2)`

Any objections to supporting the alternative behaviour?

**Comment by felixroos** [comment]
sounds useful, also for just a single number that is wrapped e.g. `n("c3").add(1)` would then work.
