### ISSUE TITLE
Reprint the "samples" tab when samples are added.

### ISSUE THREAD

**Issue by mr-eggleton** [tidalcycles/strudel#268]
When samples() is called :

```javascript
// Load the 'default samples' from tidal/superdirt
await samples('github:tidalcycles/Dirt-Samples/master')
```

Reprint the samples list in the tab (Currently starts "826 banks loaded:") to contain the new things you have loaded.

**Comment by felixroos** [comment]
good point.. lost track on that one! the samples tab is pretty underdeveloped atm

**Comment by mr-eggleton** [comment]
Was in Alex's workshop in Sheffield tonight and l noticed it pretty quickly. I'm a FoxDot user and we have a similar feature that I use all the time.

Well done on Strudel it's a great price of work and developing so fast. The kids in my Algorave club are looking forward to learning better.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by felixroos** [comment]
fixed in https://github.com/tidalcycles/strudel/pull/516 !

**Comment by felixroos** [comment]
the "samples" tab is now called "sounds", listing all sounds you can use with s , grouped into "samples", "drum-machines", "synths" and "user". It will also update live if you're loading samples via samples. Inside synths, there is now a large selection of general midi soundfonts, so you can finally write music with helicopters and gunshots 🔫 here is a demo using soundfonts: https://strudel.tidalcycles.org/?PYLKXJgtX9rV another cool thing you can do now is defining custom web audio nodes via source for full custom synthesis using the web audio api, demo: https://strudel.tidalcycles.org/?ymSQTC8hc9WC these changing involved refactoring parts of the webaudio package, so there could be some bugs floating around.. if you find one, please shout 📣  there should generally be no breaking changes (except the old, nowhere documented soundfont names do not work anymore..)
