### ISSUE TITLE
Codemirror 6

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#28]
It would be nice to update the REPL to Codemirror 6.
Here are some examples of what it brings to the table: https://codemirror.net/6/examples/
I especially like:

- [decoration widgets for custom ui elements](https://codemirror.net/6/examples/decoration/#boolean-toggle-widgets)
- [collab editing](https://codemirror.net/6/examples/collab/)
- [custom gutters](https://codemirror.net/6/examples/gutter/)

I already tested [react-codemirror6](https://www.npmjs.com/package/react-codemirror6 ) and it's pretty easy to integrate.
You can see it in action as part of [this post](https://loophole-letters.vercel.app/strudel) (The highlighting is still buggy when an event is triggered while already highlighted.).

**Comment by felixroos** [comment]
this should be a good starting point: https://github.com/felixroos/felixroos.github.io/blob/main/components/strudel/CodeMirror.jsx

**Comment by yaxu** [comment]
A big plus is that this will make strudel more accessible e.g. to people using screen readers. It'd be good to do some testing around that.
