### ISSUE TITLE
Support polymeter in mininotation

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#284]
In tidal:

`"{a b, c d e}"` = `stack("a b", "c d e".fast(2/3))`

The steps per cycle is taken from the length of the first subsequence (2 in the above), unless it's made explicit withi `%` like:

`"{a b, c d e}%4"` = `stack("a b", "c d e".fast(4/3))`

Unlike in strudel, this is a syntax error:
`"a b, c d e"`

This makes some sense, because without `{}` or `[]`, it's not explicit how the two subpatterns should be aligned.

Shall I preserve this tidal behaviour?

**Comment by felixroos** [comment]
I would be ok if `[]` is the default if no brackets are used, just because it's shorter.
