### ISSUE TITLE
compose alignments

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#304]
Currently `x.add.squeeze(y)` works but `x.every(3,add.squeeze(y))` doesn't, despite that being an example in the iclc paper

**Comment by felixroos** [comment]
aligment methods for controls are also missing: `s('sine').note.out("42 43 44")`

**Comment by yaxu** [comment]
This is working now, although that would be `s('sine').out.note("42 43 44")`, as shorthand for `s('sine').set.out(note("42 43 44"))`
