### ISSUE TITLE
voicing - major chords

### ISSUE THREAD

**Issue by adamwojt** [tidalcycles/strudel#316]
How to get plain major chords? I tried `CM` `Cmaj` `C`
Example that was given in docs:
`stack("<C^7 A7 Dm7 G7>".voicings('lefthand'), "<C3 A2 D3 G2>").note()`

**Comment by felixroos** [comment]
hey ! there are currently no built in triads, but you can do sth like this:

```js
addVoicings('triads', {
  '': ['1P 3M 5P','3M 5P 8P','5P 8P 10M'],
  'm': ['1P 3m 5P','3m 5P 8P','5P 8P 10m']
})

"<C F Fm C>".voicings('triads').note().piano()
```

see [https://strudel.tidalcycles.org?84OJ1CVICN53](https://strudel.tidalcycles.org/?84OJ1CVICN53)

Of course, triads should be part of a default set of voicings, which I will fix in the near future!

**Comment by felixroos** [comment]
addVoicings also has an optional third argument to adjust the range:

```js
addVoicings('triads', {
  '': ['1P 3M 5P','3M 5P 8P','5P 8P 10M'],
  'm': ['1P 3m 5P','3m 5P 8P','5P 8P 10m']
}, ['C4', 'C5'])
```

**Comment by adamwojt** [comment]
Thanks, but then there is no way mixing of `lefthand` and `triads` right? Eg `<C Dm7>` etc.

**Comment by felixroos** [comment]
You can do 

```js
addVoicings('triads', {
  '': ['1P 3M 5P','3M 5P 8P','5P 8P 10M'],
  'm': ['1P 3m 5P','3m 5P 8P','5P 8P 10m'],
  ...voicingRegistry.lefthand.dictionary
})
```

see https://strudel.tidalcycles.org?VmtZVDGcBEjO

Note that this feature is still in development, so there should be an easier way to do this in the future. related issue: https://github.com/tidalcycles/strudel/issues/41

**Comment by felixroos** [comment]
btw [these are the lefthand voicings](
https://github.com/felixroos/chord-voicings/blob/main/src/dictionaryVoicing.ts#L5)

**Comment by adamwojt** [comment]
Thanks @felixroos.

**Comment by felixroos** [comment]
> Thanks @felixroos.

glad to help! I'll close this now. Feel free to ask any further questions in a separate discussion or on the discord https://discord.com/invite/HGEdXmRkzT
