### ISSUE TITLE
midi() does not work inside stack

### ISSUE THREAD

**Issue by njanssen** [tidalcycles/strudel#346]
Nesting calls to `midi` in `stack` gets evaluated with success but does not result in any output:

```
stack(
  "C4*2 C5/2".note().midi('OP-Z', 1)
, "C4".note().struct("1(3,4)").midi('OP-Z', 3)
)
```

Confirmed by @felixroos that this is supposed to work. See https://www.youtube.com/watch?v=IcMSocdKwvw&t=99s

**Comment by felixroos** [comment]
should now work again! just deployed the fix

**Comment by njanssen** [comment]
> should now work again! just deployed the fix

Yes! Tried it yesterday and I was able to address multiple MIDI channels on my OP-Z inside `stack`. Good stuff 🔥

Thanks @felixroos
