### ISSUE TITLE
Small issue in the deploy manual of my-patterns

### ISSUE THREAD

**Issue by clickglue** [tidalcycles/strudel#351]
Hi Froos and Alex, thank you so much for your magnificent work on Strudel and Tidal. It has given me already many hours of joy!
When deploying 'my-patterns' in my fork of Strudel, I encountered an error:
`edit website/astro.config.mjs to use site: <your-username>.github.io/strudel and base /strudel` is not entirely correct I think, without the first `/strudel` it works as supposed. Thanks again, Guido

**Comment by felixroos** [comment]
yes you are right! just corrected it. thanks for pointing out
