### ISSUE TITLE
Highlighting not working in an application 'out' of a pattern

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#359]
e.g.: https://strudel.tidalcycles.org?bHz8qiRD_e9m

It's not clear why. As far as I can tell, `out` uses `appRight`, which does try to combine contexts in the same way as `appLeft`:

https://github.com/tidalcycles/strudel/blob/c71e893e8e46215baf9422942ba8b79490ebe3af/packages/core/pattern.mjs#L156

**Comment by yaxu** [comment]
Ah actually `s("~ ~ hh").out(n("0"))` shouldn't produce a sound anyway as the event loses its onset.

`s("hh").out(n("~ ~0"))` should work

`s("hh").set.out(n("~ ~0"))` _does_ work

So I think this is just `.out()` getting overwritten by something else.

**Comment by yaxu** [comment]
@felixroos am I right that `.out()` sends something to default output? If so can we free that up from the namespace now that it's not needed?

**Comment by felixroos** [comment]
> @felixroos am I right that `.out()` sends something to default output? If so can we free that up from the namespace now that it's not needed?

Yes that should be it. It can be removed

**Comment by yaxu** [comment]
Ok will have a look

**Comment by yaxu** [comment]
As simple as #361 ?

**Comment by felixroos** [comment]
yup looks good!
