### ISSUE TITLE
Sort haps in snapshots

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#363]
Haps can change order, e.g.:
https://github.com/tidalcycles/strudel/actions/runs/3878042120/jobs/6613770666

Maybe best to sort haps with sortHapsByPart() as part of tune and example snapshots?

**Comment by yaxu** [comment]
Does the 'arp' stuff mean that changing the order of hap lists can be a problem though?

**Comment by felixroos** [comment]
> Does the 'arp' stuff mean that changing the order of hap lists can be a problem though?

the order matters, but only within arp, so sorting them afterwards should be no problem
