### ISSUE TITLE
apply function with multiple arguments

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#383]
apply could be the pendant to layer, using seq instead of stack: https://strudel.tidalcycles.org?PmKNnp1mmPbc

like with `layer`, this means the function cannot be curried because it has variable arguments

there could also be `applycat`, `applystack` (= `layer`), `applytimecat` (that one is a bit weird) ... 🐈

**Comment by yaxu** [comment]
`apply` is patternified with `register`, so should already be sequencing multiple args.

This works:

`s("bd [bd bd]").apply(ply("3"), ply("2"), ply("8"))`

however this doesn't - seems to be a bug?

`s("bd [bd bd]").apply(ply("3"), [ply("2"), ply("8")])`

I guess we could have a 'stack' style alignment method though, so `apply.stack(a,b,c)` would be shorthand for `apply(stack(a,b,c))`

**Comment by yaxu** [comment]
Hm actually `register` doesn't sequence multiple args. Why does `s("bd [bd bd]").apply(ply("3"), ply("2"), ply("8"))` work then?

**Comment by felixroos** [comment]
ah it's a bug.. the sequence is applied here: https://github.com/tidalcycles/strudel/blob/main/packages/core/pattern.mjs#L1650 (why only with arity 2 though?) but the args passed to sequence are already reified, so the array is replaced with a Pattern of an array.. it works by moving the reification down
