### ISSUE TITLE
https://strudel.tidalcycles.org/tutorial/: every(n, func) examples cause: "evaluation error: b4 is not defined" 

### ISSUE THREAD

**Issue by bwagner** [tidalcycles/strudel#39]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/447049/162810590-5ebc6894-5e2b-45a7-8784-efd1a1f56785.png">

**Comment by felixroos** [comment]
fixed with https://github.com/tidalcycles/strudel/commit/7ca8c8d2981597311faf3b50c502c2b7aac917a9
