### ISSUE TITLE
add simpler version of Pattern.query

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#42]
this is bulky: `pattern.query(new State(new TimeSpan(0, 1)))`. It would be cool to have a way to query by just passing numbers. One of:

- `pattern.query(0, 1)` <- this would require "overloading" the function by type checking
- `pattern.queryArc(0, 1)` <- this would just be plugging `.query(new State(new TimeSpan(begin, end)))`

**Comment by yaxu** [comment]
Is this just to help with debugging?
If so we could call it `pattern.show()`, have it print the first cycle by default, and also do pretty printing, therefore returning a string rather than a list of haps.
Or is it to simplify the API?

**Comment by felixroos** [comment]
More to simplify the API. It feels wrong to write about strudel, and the first thing you see is `pattern.query(new State(new TimeSpan(begin, end)))`. Thinking more of users of the js library here. Maybe it's easiest just to add `queryArc` as sugar, possibly with additional state as third param

**Comment by felixroos** [comment]
fixed with 2060e868750c649bc84f67d1d0b330b925dd4262
