### ISSUE TITLE
automate repl / tutorial build

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#43]
currently, building the repl must be done manually. it would be cool if each push to main would trigger a rebuild.
the repl and the tutorial can be built with `cd repl && npm run build`. currently this will move the build to `/docs` folder, but it could be smarter to use `gh-pages` branch instead.

This would also automatically update the tutorial when people make edits from github directly, which is nice

**Comment by yaxu** [comment]
Perhaps a push to `gh-pages` could build strudel.tidalcycles.org, and a push to `main` could build strudel-secret-preview.tidalcycles.org

**Comment by felixroos** [comment]
i like the idea of having two environments, but I think github pages only allows one. 
I also thought it would be handy to somehow reflect the strudel version as part of the url, to make sure old links keep working after breaking changes. But this could also be a challenge to build..

On the other hand, this works out of the box with githack: https://raw.githack.com/tidalcycles/strudel/ee0d835cd88731f05704536536a9ca31b7f8b4e8/packages/core/examples/canvas.html but this will only work if the html file is standalone and doesn't require a build (which is generally possible with skypack). but maybe this is a seperate issue

**Comment by felixroos** [comment]
I have now created the "Build and Deploy" workflow which can be triggered from the Actions tab. It builds the REPL and tutorial and deploy it to github pages, so now the project can be published with the click of a button! Deploying automatically on push to main seems overkill to me..

With this setup, we can also roll back deployments to specific tags, which is a good safety net.
