### ISSUE TITLE
Documentation permalink problems

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#432]
See e.g. the permalinks on [this page](https://strudel.tidalcycles.org/learn/conditional-modifiers). 

1. They go to root rather than current page
2. You have to mouseover the headings and carefully move to the left to get to the link, which is a bit tricky. [Github README.md](https://github.com/tidalcycles/strudel#readme)'s look the same but you can directly mouseover where the link icon is going to appear rather than go via the heading.

**Comment by felixroos** [comment]
now fixed and deployed! the anchors are now right to the headings with "#" and also show on hover the heading

**Comment by yaxu** [comment]
Great thanks!
