### ISSUE TITLE
docs: footnote not working

### ISSUE THREAD

**Issue by bwagner** [tidalcycles/strudel#439]
This page: 
https://strudel.tidalcycles.org/technical-manual/repl
contains a footnote:
`REPL^[REPL stands for read, evaluate, print/play, loop. It is friendly jargon for an interactive programming interface from computing heritage, usually for a commandline interface but also applied to live coding editors.]`
which does not get rendered as expected.

**Comment by felixroos** [comment]
i'd say having footnotes in the docs is not really needed.  I've converted it to using parens for now. closing this. if anyone desperately needs footnotes, please reopen or send a PR :P
