### ISSUE TITLE
Pseudo-randomness

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#46]
A first step would be to implement the `rand` signal, then the other random functions can be implemented based on that.

Ideally this would give identical results to Tidal's RNG, although I guess depends on javascript and haskell having the same implementation of floating point numbers:
https://github.com/tidalcycles/Tidal/blob/main/src/Sound/Tidal/UI.hs#L46

Also in the process of writing this issue, I've noticed a couple of problems with tidal's `rand`:
https://github.com/tidalcycles/Tidal/issues/905

**Comment by felixroos** [comment]
Good to know that randomness is only pseudo random, because it will make sure graphics that look further in to the future will have the same result

**Comment by yaxu** [comment]
Yes there are some problems with this approach, like in this:
```javascript
s("bd*16").pan(rand).speed(rand)
```
High speeds would always be panned to the same place. But then you can get a different stream like:
```javascript
s("bd*16").pan(rand).speed(rand.slow(1.0001)
```
