### ISSUE TITLE
looping samples

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#499]
there is already `loop`, but it could be extended with `loopStart` / `loopEnd` to set a loop the sample runs into.
this is nice for creating sustained notes from samples, like soundfonts do. the implementation should be pretty easy, as webaudio already supports loopStart and loopEnd. probably need to respect `begin` and `end`...

**Comment by yaxu** [comment]
`loopBegin` might fit better with `begin`

**Comment by felixroos** [comment]
fixed with: https://github.com/tidalcycles/strudel/pull/698
