### ISSUE TITLE
List parsing in mininotation

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#504]
It would be nice if `:` in mininotation created a list, i.e. `mini("a:b:c")` was the same as `pure(['a', 'b', ''c'])`. That would support easy implementation of multi-parameter thingies like `adsr("0.5:<0.4 0.6>:0.6:0.1")` and make parts of a scale identifier patternable like `scale('c:<major minor>')`.

One problem: how should the patterned elements be combined? Apply in to the left is standard, but would 'mix' make more sense here? Do we want to add extra syntax for alternatives, and if so should that be just in/out/mix, or also squeeze, trig etc..?

**Comment by felixroos** [comment]
ref: https://github.com/tidalcycles/strudel/discussions/172#discussioncomment-5189360
chords would then also be patterned like that? e.g. `"c:<min7 maj7>"`

**Comment by yaxu** [comment]
Sorry about all the noise from late night git troubles..

But #512 can now parse lists like `"a:b:<c d>"

and even multi-dimensional lists `"[[a:b]:[c:d]]"`

**Comment by yaxu** [comment]
> chords would then also be patterned like that? e.g. `"c:<min7 maj7>"`

yep!
