### ISSUE TITLE
Switch shortcuts to use e.key rather than e.code

### ISSUE THREAD

**Issue by alistair-marshall** [tidalcycles/strudel#528]
Could we swap the shortcuts from using `e.code === 'Period'` to `e.key == '.'`?

I accept that I am awkward, but I use the [Dvorak keyboard](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout) and this causes a problem with the current strudel keybindings.

Whenever I attempt to paste something (ctl + V), the actual key code generated is that of 'period', so strudel stops playing (and nothing is pasted). The only way I can paste is to right click with the mouse (which is a bit of a pain).
If the event key were to be used, I would be able to stop the music as normal using ctl + . and I would also be able to paste values from the clipboard. It would also allow re-evaluation if someone uses the enter key on the numpad.

I hope this makes sense.

**Comment by felixroos** [comment]
that sounds reasonable! we just have to make sure the change does not introduce a regression, so checking on different systems is needed

**Comment by alistair-marshall** [comment]
Thanks.

Just tested and works great!
