### ISSUE TITLE
sample server / strudel.json generator

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#536]
it would be nice if there was an easy to use solution for using sample folders. following things could be done

## strudel.json generator script

provide a script that outputs a strudel.json from a folder. without user input, the sample folder requires a specific structure. also pitch zones would not be supported / would require manual adjustments. the strudel.json could either be copy pasted into the repl or be pushed to a repo. a repo is not always the solution because you might not want to upload your samples publicly.

with a repo, it could be used like:

```js
samples('github:felixroos/samples/main')
s('flute')
```

without a repo, a local file server can be started via `npx serve ~/Music/Samples --cors` (required nodejs).
The strudel.json can either be copy pasted like that:

```js
samples({
  // copy pasted content of generated strudel.json
  flute: 'path/to/flute.wav'
})
s('flute')
```

or the server url is used:

```js
samples('localhost:3000')
s('flute')
```

## sample server

a bit more sophisticated than 1, there could be a sample server that runs inside a specific folder like `npx strudel-sampler ~/samples`, providing `localhost:1234/strudel.json` that automatically reflects the folder. the server could then be used like

```js
samples('http://localhost:1234/');
s("mysound")
```

this is just simpler to use, as the previous approach requires running a script and then a file server, while this approach only requires to run a single command.

## sample server with ui

a bit more sophisticated than 1&2, the sample server could also have a ui that can be visited on `http://localhost:1234` or similar.
That ui could be used to browse the samples and customize the strudel.json, allowing to create pitch zones / reorder things / ignore things / use deeper file nesting / create banks etc....... the ui could even be built into a sample editor to create slices. It even might have midi capabilities to connect with a launchpad to play the samples..... so much potential..
anyways, when the user is done editing, the strudel.json has to be persisted to the disk, to not loose the data when the server is closed. this also means that the server has to detect a pre-existing strudel.json file on startup to not generate the default one.

## not using a separate server?

the alternative to using a separate sample server would be to use the strudel website itself to provide that behavior, using the file system access api instead of a node server. this approach would be even simpler but unfortunately, firefox does not support that api. related issue: https://github.com/tidalcycles/strudel/issues/118

**Comment by alistair-marshall** [comment]
I really like the idea of enhancing the strudel website itself to provide the behaviour and minimising any other install requirements. It would also be nice to provide an easy way to browse/preview the existing loaded samples within the strudel UI.

As for firefox not supporting the api, the fallback could be download the strudel.json file and instructions on how to run a local web server such as the python version (python usually available on macos/linux - may need another solution for windows).

**Comment by ilesinge** [comment]
A very quick adaptation of https://raw.githubusercontent.com/dktr0/estuary/dev/generateAudioResources.sh I did for Strudel can be found here:
https://gist.github.com/ilesinge/a3782e7b918f26833f17cc5dbf2bf755
The _base URL must be changed every time though.

I am also working on an easy to use (no tech knowledge needed) multiplatform tool for that too, it could probably launch a webserver.

**Comment by ilesinge** [comment]
As commented earlier, here is the small cross-platform (Linux/MacOS/Windows) tool to generate samples JSON files and to expose the samples locally (without additional dependency). It supports both Estuary and Strudel: https://github.com/ilesinge/samples4web
(let me know if you have improvement suggestions)
I like the idea of having a specific UI to manipulate the JSON or the samples.

**Comment by felixroos** [comment]
with https://github.com/tidalcycles/strudel/pull/621 , samples can be loaded from the desktop app, without the need for a server! The benefit is that you don't need extra tooling (npm / python). It also automatically generates a strudel.json file when a directory is first loaded and then reuses it. 
I'd say with https://github.com/ilesinge/samples4web that works well for the website and the built in functionality of the desktop app, we don't need another solution for that. It would still be great to have a ui that allows to edit the strudel.json, maybe that could also be part of the desktop app at some point.
I'll close this issue and create a follow up issue for that!

**Comment by felixroos** [comment]
follow up issue: https://github.com/tidalcycles/strudel/issues/624
