### ISSUE TITLE
compound adsr control

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#541]
as proposed in https://github.com/tidalcycles/strudel/discussions/515

something like:

```js
s('flute').adsr("[.1:.1:.2:.1]")
```

or using params:

```js
s('flute').adsr(.1, .1, .2, .1)
```

lists have the advantage that values can be optional, while with params, everything must be specified at all times. not sure though

**Comment by rabidmachine9** [comment]
Hopefully what I say will be relevant, but I believe there is some difference between adsr applied on a sample and adsr when used in sound synthesis. When in sound synthesis almost every value makes sense, that is not the case when you are trying to apply your envelope on a sample, in the latter case the sum of your Attack + Decay + Release values needs to be smaller than the size of the sample. So I guess my question is, what do these numbers represent ? And in my opinion they should mean something like 
Attack: 0.1 * sampleLength, 
Decay: 0.1 * sampleLength, 
Sustain: play the rest of the sample with 0.2 amplitude and leave 0.1*sampleLength for the release,
Release: 0.1 * sampleLength

**Comment by rabidmachine9** [comment]
And maybe, an interface like env(.2, .6) (that means go to 0.6 in 0.2*sampleLength) would be more relevant for samples. 
And you can take it a step further by doing something like env([.2,.6], [.3,.4],...)

**Comment by felixroos** [comment]
>  there is some difference between adsr applied on a sample and adsr when used on a sound generator.

it depends how it is implemented i'd say. at the moment, strudel applies the same envelope, no matter what type of sound. If the sound is shorter than the envelope, then you just won't hear the end of the envelope, because the sound is already out. I actually like the behavior because it is clear and always the same. It is also how it would work in a modular synth when you have a drum machine plugged into an envelope.

Still, it would be nice to have an envelope that is relative to the hap duration or sample duration. But that should be a separate issue I think. The idea behind this issue is to just have a shorter way of setting the attack / decay / sustain / release params, not how they should work.

Maybe what you're looking for is also [this issue](https://github.com/tidalcycles/strudel/issues/561) (make sure to read the later comments)

**Comment by felixroos** [comment]
fixed with https://github.com/tidalcycles/strudel/pull/587
