### ISSUE TITLE
Midi output lost when window loses focus

### ISSUE THREAD

**Issue by boonier** [tidalcycles/strudel#549]
Hi, this is a fantastic bit of software! Looking forward to future developments...

I've noticed both in the browser, or in offline version as an app, the midi notes don't exactly stop, just outputs burst of notes when the window is out of focus.

When in focus there is no problem. 

Is this a current restriction of the browser? I'm aware JS timers are throttled or disabled in the background, unless if they are in Workers. But looking at the code in `zyklus.mjs`, the clock is in the main thread using the audio clock to schedule events. 

Is this a known issue?

cheers

ps. I'm using Brave browser.

**Comment by felixroos** [comment]
hey, thanks for reporting! I don't have Brave so I cannot test, but I am pretty sure it's the browser. Firefox and Chromium don't throttle inactive tabs afaik, at least everything keeps playing when the tab is out of focus. Does the same thing happen with web audio, or is it just a midi problem? what os are you using?

**Comment by felixroos** [comment]
Just realized Brave is chromium based, but they maybe use an old version of chromium where interval throttling was still a thing

**Comment by felixroos** [comment]
this could help: https://www.reddit.com/r/incremental_games/comments/jefviz/fyi_how_to_disable_timer_throttling_on_google/ brave flags are probably under `brave://flags` if not `chrome://flags/`

would also be interesting to know if the same happens here: https://loophole-letters.vercel.app/web-audio-scheduling#revisiting-the-tale-of-two-clocks

I thought the timer throttling was a thing of the past, but maybe some browsers still do it.. then it should make sense to use a worker for the clock

**Comment by boonier** [comment]
Sorry for not replying sooner!

Brave doesn't appear to have that flag.

Actually this is happening on both versions of Strudel - in the browser and as a desktop app (both Brave). Also strange is that if Strudel is in the background overlayed by another window, but you can still see a bit of it:

![image](https://user-images.githubusercontent.com/6206789/233343334-80c04abe-395d-46b6-b631-4ff4e34f784d.png)

midi output is fine, but when it is totally obscured like:

![image](https://user-images.githubusercontent.com/6206789/233343523-3f1bb574-5f14-42a3-be0d-145f444bc3cf.png)

midi starts to fall apart!

**Comment by boonier** [comment]
Same in Chrome btw

**Comment by boonier** [comment]
>I thought the timer throttling was a thing of the past, but maybe some browsers still do it.. then it should make sense to use a worker for the clock

but does that not mean that you lose the precision of the audio clock context? (because you can't access the main thread directly from a worker)

I've read some about this, heavy stuff but this looks promising!

https://github.com/padenot/ringbuf.js

**Comment by felixroos** [comment]
> I've read some about this - exposing AudioContext in a Worker - heavy stuff, and whilst not being implemented, this looks promising!

Yep, experimenting with AudioWorklets is planned for the future. Though it should be noted that live coding is not that real time critical, as super low latency is not really needed. We're currently at 50ms and it feels really snappy I'd say.
I wrote a little more on that at the end of [this comment](https://github.com/tidalcycles/strudel/issues/561#issuecomment-1540846477). 

> Same in Chrome btw

Oh that's interesting.. It seems to be a problem with WebMidi only and not with the audio loop. If you don't use midi, a minimized tab happily continues to run. There has to be some WebMidi specific, not sure how it works. That means changing the scheduling won't help I suppose.

**Comment by boonier** [comment]
Ah I see, right. I'm coming at this relatively high level, compared to you :) so I don't mean to point out things you've no doubt thought about and put to rest!

Everything is bound by time in one way or another, and audio scheduling is fearsomely tricky to get right, as I'm discovering. JS and web audio is no exception. You've got a great blog btw, I just made the connection between that and Strudel!

> There has to be some WebMidi specific

Seems so, doesn't it?
