### ISSUE TITLE
update vitest

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#554]
vitest is currently on ^0.25. most newer versions fail with this error: "No test suite found in file" even though the tests are the same as before. I then tried a bunch of versions, including some of the past, to find this pattern:

```
^0.21.0: Cannot read properties of undefined (reading 'matchers')
^0.22.0: Cannot read properties of undefined (reading 'matchers')
^0.23.0: No test suite found in file
^0.24.0: No test suite found in file
^0.25.0: works
^0.26.0: No test suite found in file
^0.27.0: No test suite found in file
^0.28.0: works
^0.29.0: No test suite found in file
^0.30.1: No test suite found in file
```

Since 0.25, there have been some breaking changes

https://github.com/vitest-dev/vitest/releases/tag/v0.26.0
https://github.com/vitest-dev/vitest/releases/tag/v0.27.0
https://github.com/vitest-dev/vitest/releases/tag/v0.28.0
https://github.com/vitest-dev/vitest/releases/tag/v0.29.0
https://github.com/vitest-dev/vitest/releases/tag/v0.30.0

I guess thats what they call bleeding edge tech.. maybe just wait a little bit more to have it fixed.
There is probably som error shadowing going on..

related issues:

- https://github.com/vitest-dev/vitest/issues/2840
- https://github.com/vitest-dev/vitest/issues/2032
- https://github.com/vitest-dev/vitest/issues/847
- https://github.com/vitest-dev/vitest/issues/2604

**Comment by bwagner** [comment]
I had problems (`No test suite found`) with vitest 0.25.0 and 0.28.0, but 0.33.0 worked fine.

**Comment by felixroos** [comment]
> I had problems (`No test suite found`) with vitest 0.25.0 and 0.28.0, but 0.33.0 worked fine.

yep 0.33.0 works fine for me. let's hope they fixed the problem once and for all
