### ISSUE TITLE
Links to manual bring up the REPL?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#569]
For example if I follow a link to:
https://strudel.tidalcycles.org/technical-manual/alignment/

The last strudel pattern I played at comes up instead.

If I do a hard page refresh then the manual appears.

**Comment by felixroos** [comment]
hm weird stuff happening.. maybe some cache interference going on. Maybe just link https://github.com/tidalcycles/strudel/blob/a03541295627ee7f1a6df545a61dd9ab7b68d421/website/src/pages/technical-manual/alignment.mdx for now :-/

**Comment by felixroos** [comment]
it works without the slash at the end: https://strudel.tidalcycles.org/technical-manual/alignment

**Comment by felixroos** [comment]
found the problem, described here: https://github.com/vite-pwa/astro/issues/23#issuecomment-1773447037

**Comment by felixroos** [comment]
fixed with https://github.com/tidalcycles/strudel/pull/753
