### ISSUE TITLE
UX proposal: repl sidebar

### ISSUE THREAD

**Issue by roipoussiere** [tidalcycles/strudel#574]
I find the bottom bar a bit disturbing. Among other things, it adds many scroll bars in the UI (see image below), an extra menu bar, and takes some space.

I wonder if it can be removed. Here are some suggestions to achieve this:

- `welcome`, `reference` and `sound` could be displayed as full-screen windows appearing when clicking on corresponding items in a new **help** menu located in the top bar (and so the current *learn* button could be part of it);
- `console` could be en/disabled by moving a slider (so we can also set its size);
- `settings` could be displayed as a full-screen window when clicking on a new **settings** button in the top bar.

I can try to work on it if you think it's a good idea.

---

![image](https://github.com/tidalcycles/strudel/assets/1665542/46636f03-93b6-4ae1-ae4f-f9c8e07feeaa)

**Comment by felixroos** [comment]
> it adds many scroll bars in the UI

I'd say that's more a css bug.. I haven't noticed it yet, likely because my browsers / systems use floating scrollbars, so I only see the scrollbar that's actively used. So at least the second scrollbar could be removed by tweaking the style.

> and takes some space

you can also click the strudel icon to enter "zen mode" :) 

> I wonder if it can be removed

I kind of like the bottom bar. Especially for sounds and reference, imho it makes more sense to not have a full screen so you can quickly copy paste stuff around. It is also likely that the bottom bar will be extended / extendable in the future.

So maybe start by fixing the scrollbar? Maybe it's less disturbing already then? Would you want to try that?

We could maybe also add different UI variants under different routes, e.g. strudel.tidalcycles.org/xxx

**Comment by roipoussiere** [comment]
> I kind of like the bottom bar. Especially for sounds and reference, imho it makes more sense to not have a full screen so you can quickly copy paste stuff around. It is also likely that the bottom bar will be extended / extendable in the future.

Ok I understand. When the bottom bar is open, there is a just a few lines of code displayed in the editor, so I can't easily use both the editor and the bottom bar content.

Also, the content of the current bottom bar seems to be better appropriate for a less wide container (see unused area bellow).

![image](https://github.com/tidalcycles/strudel/assets/1665542/214dfba5-99b1-4c4f-9c58-a93427e5dfb7)

So what about a side bar with editable width? We can have many lines of code displayed in the editor, while easily accessing the sounds, reference, etc. and have it bigger or smaller if necessary. He is a quick mock-up:

![image](https://github.com/tidalcycles/strudel/assets/1665542/30b92b5f-be8b-47a6-b1dc-d2029813651a)

**Comment by felixroos** [comment]
yep that seems useful. there could be a toggle button to switch between side and bottom bar. the bottom bar should be resizable as well.

**Comment by felixroos** [comment]
I can also take a look at this

**Comment by roipoussiere** [comment]
When the screen width is small, like in responsive websites.

For me the only use case of wanting the tabs on the bottom is when we are on mobile, because the content in the tabs are not so wide. And it avoids adding the toggle button, so the interface is lighter.

**Comment by felixroos** [comment]
> When the screen width is small, like in responsive websites.

This would also place the bar on the right on mobile, which is not ideal..

> And it avoids adding the toggle button, so the interface is lighter.

The toggle could be another setting, so the interface will stay light. I don't think it is a bad thing having a healthy degree of customizability. For example, look at [p5live](https://teddavis.org/p5live/), which has ~15 checkboxes to toggle different things..
I'd rather have one more checkbox than a UI that I cannot change when it does not do what I want.

**Comment by felixroos** [comment]
now tracking in https://github.com/tidalcycles/strudel/issues/600
