### ISSUE TITLE
Add option to display line numbers

### ISSUE THREAD

**Issue by roipoussiere** [tidalcycles/strudel#575]
It can be really useful to have line numbers in the editor, like in many IDE. The console can displays error messages with line numbers (ex: `[eval] error: Unexpected token (26:0)` and it's obviously tedious for the user to count them.

I can work on it if necessary.

**Comment by felixroos** [comment]
yep certainly useful! It would be good if it could be enabled / disabled via a checkbox in the settings.
Codemirror already has a [built in feature](https://codemirror.net/docs/ref/#view.lineNumbers) for that
