### ISSUE TITLE
Add option to put bottom-bar on the side

### ISSUE THREAD

**Issue by hellocatfood** [tidalcycles/strudel#600]
Can there be an option to put the bottom bar on the right side? Most displays have more horizontal space than vertical space, so I think it makes more sense to use the horizontal space. For example, in this mockup (based on my 16:10 display) of putting the bar on the right side there's still plenty of space for the code and content of the sidebar.

![Screenshot from 2023-06-13 13-53-34_mockup](https://github.com/tidalcycles/strudel/assets/151947/ca916cf6-c6da-46ae-a38c-818b366db4e1)

**Comment by felixroos** [comment]
yep makes sense! already proposed in https://github.com/tidalcycles/strudel/issues/574 so I'll close this one

**Comment by felixroos** [comment]
actually, let's use this one.. #600 :)
