### ISSUE TITLE
ratio function

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#601]
allows using ":" as a division sign. very cool for writing in just intonation!

example https://strudel.tidalcycles.org/?O1gumBUFA-o2

**Comment by yaxu** [comment]
In Tidal this is done with the `%` character, e.g. `1%3` for a third. It's a bit ugly but memorable. There's also some shorthands, e.g. `t` for third, `f` for fifth, although relies on type inference to avoid the clash with notes.

**Comment by felixroos** [comment]
Didn't know about % in tidal.. 

> Being able to pattern numerator and denominator separately is nice, that's not currently implemented in tidal..

Yep, the whole ":" syntax is quite powerful and opens a range of possibilities. I like the idea that the function can choose what to do with lists.
