### ISSUE TITLE
Line numbers for mininotation errors

### ISSUE THREAD

**Issue by amiika** [tidalcycles/strudel#608]
Mininotation errors messages do not print line numbers. This makes it tricky debug if there are multiple lines using mininotation.

Other errors like missing commas do already give line numbers like so: Unexpected token (8:2)

**Comment by felixroos** [comment]
[this could be used](https://peggyjs.org/documentation.html#error-reporting)

**Comment by felixroos** [comment]
fixed with https://github.com/tidalcycles/strudel/pull/880
