### ISSUE TITLE
Allow to write signals like functions.

### ISSUE THREAD

**Issue by roipoussiere** [tidalcycles/strudel#609]
I wander why `saw`, `sine` etc. must be written without parenthesis.

If I take a quick look at the [source code](https://github.com/tidalcycles/strudel/blob/main/packages/core/signal.mjs#L35), I can see they are actually functions.

There are other functions like `log()`, that doesn't take any parameter but are written with parenthesis.

Also `irand` is a signal but takes a parameter so it's written with parenthesis: we write `rand.range(500,2000))`, but `irand(8).range(20, 30).segment(24).note()`, so it's not really consistent.

I also think that signals written like this can be confused with variable names.

I suggest to allow to write `rand()`, `sine()`, etc.

**Comment by yaxu** [comment]
They aren't functions, they are pattern objects.

The `signal` function takes a function as an argument, and returns a pattern.

It's true to say that a pattern object is a kind of wrapper around a function, as patterns are represented as functions of time. However, such functions (known as pattern 'queries') are called by the scheduler, not by the end-user.

**Comment by roipoussiere** [comment]
Thanks for the clarification.
Sorry for this issue, I should have ask for some explanation in the discussion section first.

**Comment by yaxu** [comment]
No problem at all! Don't hold back with questions and issues :)
