### ISSUE TITLE
fit sample to hap duration

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#619]
https://strudel.tidalcycles.org/?OvRRzXwrKDl8

name is up for debate, fit is already taken in tidal

**Comment by yaxu** [comment]
A version that works with sample slices with begin / end:

https://strudel.tidalcycles.org/?PS9_K51kXKZ5

**Comment by felixroos** [comment]
already done with https://github.com/tidalcycles/strudel/pull/620
