### ISSUE TITLE
browsable patterns

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#644]
add a tab with all example patterns + patterns created by the user. the user patterns can be saved to the local storage. Inspired by https://teddavis.org/p5live/ . The desktop version could maybe also include local .strudel files.

**Comment by jarmitage** [comment]
Also add a button to import/export all user patterns in a Json file

**Comment by jarmitage** [comment]
If it's sidebar based, maybe there could be a button to toggle between list of files and pattern swatches?

**Comment by jarmitage** [comment]
Autocomplete / "Insert at point" feature would be nice to retrieve stored patterns directly into the current editor

**Comment by felixroos** [comment]
this now exists as the patterns tab. moved the above ideas to this follow up issue: https://github.com/tidalcycles/strudel/issues/1019
