### ISSUE TITLE
The csound output does not trigger the onTrigger pattern

### ISSUE THREAD

**Issue by gogins** [tidalcycles/strudel#658]
The following Strudel patch can be pasted into the REPL and demonstrates the issue:

[csound_trigger.txt](https://github.com/tidalcycles/strudel/files/12304850/csound_trigger.txt)

If the `csound` output is enabled by uncommenting line 51, then the Csound output plays, but the `onTrigger` pattern is not triggered, and the generated notes do not climb in pitch. If the `csound` output is disabled by commenting out line 51, then the piano output plays, the `onTrigger` pattern _is_ triggered, and the generated notes _do_ climb in pitch.

**Comment by felixroos** [comment]
yes, that is to be expected, because Pattern.csound will override the .onTrigger on the hap context. having multiple triggers is not implemented yet.. but it could be done easily, by just collecting triggers in an array.

**Comment by gogins** [comment]
What about using a non-dominant trigger for the Csound output, as in the stateful pattern example?

**Comment by felixroos** [comment]
> What about using a non-dominant trigger for the Csound output, as in the stateful pattern example?

it still wouldn't work to call onTrigger 2 times, as the second call will always override the "onTrigger" property of Hap.context. it might be clearer by [looking at the source](https://github.com/tidalcycles/strudel/blob/main/packages/core/pattern.mjs#L781)

**Comment by felixroos** [comment]
this is the other relevant place: https://github.com/tidalcycles/strudel/blob/main/packages/core/repl.mjs#L82
the csound output (and similar ones) would need to override the defaultOutput (which is what dominantTrigger does) but still call pre-existing triggers.. so maybe it will already be fine if

```js
 if (!dominant && hap.context.onTrigger) {
```

is changed to 

```js
 if (hap.context.onTrigger) {
```

the question would be if there is a use case where you would want to ignore an existing onTrigger callback..

**Comment by gogins** [comment]
I have implemented your suggestion in my local Strudel and it seems to work fine without messing up existing pieces in the REPL "Shuffle."

**Comment by felixroos** [comment]
should now be fixed. there was another weird behavior when you'd add a non-dominant trigger after a dominant one, then the default output would be activated again.

**Comment by gogins** [comment]
This is no longer working as I expected. The attached patch can be run to demonstrate the issue.

- For the default output, the notes appear to be correctly computed but the piano roll jumps up and down during performance.
- For the `csound` output, the notes are not correctly computed; the value of `state` is computed, but is not added to the notes going to Csound.

[csound_trigger.txt](https://github.com/tidalcycles/strudel/files/12339955/csound_trigger.txt)

**Comment by felixroos** [comment]
the changed merged in https://github.com/tidalcycles/strudel/pull/660 is not yet deployed so nothing should've changed, which means .csound will still overwrite your trigger. without csound, the piano roll jumping around is to be expected because you're using global state that is not integrated with the used patterns

**Comment by felixroos** [comment]
now it's deployed, so now the onTrigger will always get called (with or without csound being used).

**Comment by gogins** [comment]
I made to sure to completely clear my browser cache and application data. The deployed REPL now does play notes with the added state, both for the default output and for the Csound output. Thanks for that!

However, the pianoroll display is still jumping up and down in both cases.

**Comment by felixroos** [comment]
> However, the pianoroll display is still jumping up and down in both cases.

yes, that is because you're using an external state variable inside the withHap callback, turning it into a non-pure function, breaking the whole pure functional programming paradigm. As said earlier, it's not a solution, it's a workaround.
The pianoroll jumping around is only one symptom, you will also not be able to use pattern methods as expected.
I'd recommend trying to solve your problem without state (if possible).

in tidal, this problem is already solved like this: https://tidalcycles.org/docs/reference/state_values/
