### ISSUE TITLE
flip chunk and chunkBack, and match behaviour of tidal

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#689]
as reported by @yaxu "chunk and chunkBack seem to be the wrong way around https://strudel.tidalcycles.org/?vk6mTUMljbp7"

**Comment by yaxu** [comment]
In tidal, chunk does all the chunks of the first cycle before moving on to the second:
```haskell
fast 4 $ chunk 2 (+10) $ "[0 1 2 3]/2"
(0>⅛)|10
(⅛>¼)|1

(¼>⅜)|0
(⅜>½)|11

(½>⅝)|12
(⅝>¾)|3

(¾>⅞)|2
(⅞>1)|13
```

That's not the case with strudel, so you get a simpler output with shorter repeat:
```javascript
mini("0 1 2 3").slow(2).chunkBack(2, x => x.add(10)).fast(4).firstCycleValues
Array(8) [ 10, 1, 2, 13, 10, 1, 2, 13 ]
```

Probably we should replicate the tidal behaviour in strudel. But maybe keeping the old behaviour under a different name? Could be `chunkFast` ?

**Comment by felixroos** [comment]
> Probably we should replicate the tidal behaviour in strudel. But maybe keeping the old behaviour under a different name? Could be `chunkFast`

makes sense!

**Comment by yaxu** [comment]
I thought `fastChunk` would be better to match `fastCat`
