### ISSUE TITLE
Failure to build on MacBook Pro 14 with M1 chip, macOS 13.5.1

### ISSUE THREAD

**Issue by gogins** [tidalcycles/strudel#696]
TL;DR: Clone fresh repo, run `npm run setup`, then run `npm run dev` which fails to build. See attached log for details.

[log.txt](https://github.com/tidalcycles/strudel/files/12554185/log.txt)

**Comment by felixroos** [comment]
try with node 18?

**Comment by gogins** [comment]
That worked, thank you. 

This should be mentioned in the README.md.
