### ISSUE TITLE
Support patterning euclidean values in the mininotation

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#72]
e,g `"a3(<3 5>,8,<0 2 4>)"`

**Comment by charlieroberts** [comment]
perhaps this should be its own bug, but in a similar vein, `0*<12 8>` will also fail to parse

**Comment by yaxu** [comment]
@charlieroberts #341 fixes that too :)

**Comment by charlieroberts** [comment]
awesome!!!!!!!
