### ISSUE TITLE
idea: support international alphabets in sample names

### ISSUE THREAD

**Issue by ilesinge** [tidalcycles/strudel#750]
As a non-English natively speaking user, I would like to have sample names in my mother tongue (especially spoken words).

Currently, only alpha-numeric characters are allowed in the [parser](https://github.com/tidalcycles/strudel/blob/main/packages/mini/krill.pegjs#L106).

This would be particularly interesting in combination with the speak function and with shabda's speech mode, which both do direct step name to voice generation and thus cannot be used currently with some non-English languages in mininotation.

Looking at [this pegjs issue](https://github.com/pegjs/pegjs/issues/226#issuecomment-32122017) and after experimenting that the [Unicode Character Categories such as \p{Letter}](https://dev.to/tillsanders/let-s-stop-using-a-za-z-4a0m) are not supported in pegjs, it would seem that the most obvious, if not elegant, solution, would be to add all alphabets in the parser such as in [the example JavaScript parser](https://github.com/pegjs/pegjs/blob/93d3c6a2509f947f57d5728c15d8b96ceedef28f/examples/javascript.pegjs#L387).

**Comment by felixroos** [comment]
yep i'd also love to use german special chars sometimes + using emojis would be cool too

**Comment by ilesinge** [comment]
The pull request adds german special chars (but excludes emojis), if you want to have a look (not super satisfied about it but I go around pegjs limitations)

**Comment by felixroos** [comment]
fixed in https://github.com/tidalcycles/strudel/pull/751
