### ISSUE TITLE
Strudel overlays text in zen mode

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#757]
Observed in firefox and chrome under linux:

![image](https://github.com/tidalcycles/strudel/assets/27940/4afca2be-bd86-4213-8cc5-8b25fb178f7b)

**Comment by felixroos** [comment]
yep having the same issue. maybe just add padding left and right when zen mode is on? like this:
<img width="653" alt="image" src="https://github.com/tidalcycles/strudel/assets/12023032/3362828a-d7d1-4971-9f6a-273db8db8baf">
