### ISSUE TITLE
line numbers broken

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#778]
probably since https://github.com/tidalcycles/strudel/pull/773 the line numbers cannot be toggled on anymore

**Comment by Dsm0** [comment]
Drat... my apologies
I'm not encountering this issue locally on chrome or firefox, but am on the site.
I'll try to look into it

**Comment by felixroos** [comment]
> Drat... my apologies I'm not encountering this issue locally on chrome or firefox, but am on the site. I'll try to look into it

no problem, not even sure it was your PR, as I merged a bunch of other ones too

**Comment by Dsm0** [comment]
@felixroos have you been able to observe the issue occurring on a locally run instance? I have no clue what it could be

**Comment by felixroos** [comment]
> @felixroos have you been able to observe the issue occurring on a locally run instance? I have no clue what it could be

i can reproduce it locally when i build the site for production using `pnpm build && pnpm preview`. But not sure what it is, can look more closely tomorrow

**Comment by felixroos** [comment]
@Dsm0 I found the issue, it was not at all related to your PR, sorry for the blame :P It was just a style bug that popped up after updating the site generator, fyi more info here: https://github.com/tidalcycles/strudel/pull/781
