### ISSUE TITLE
Enable function tooltip on code hover

### ISSUE THREAD

**Issue by ilesinge** [tidalcycles/strudel#782]
As a newbie (or constant learner) I would like to easily understand code from an existing piece or from my own exploration.

A classic way to do that would be to expose strudel functions documentation via tooltips when hovering code.

I have made an example implementation, where pressing the Ctrl key is needed in addition to hovering a word (Pull Request to follow).

**Comment by ilesinge** [comment]
See screenshots in the linked PR: https://github.com/tidalcycles/strudel/pull/783
As the feature is optional, would you rather like the tooltip to be always shown (without pressing the Control button)?
It helps feature discovery, but it can be a bit overwhelming when you see tooltips everywhere.

**Comment by felixroos** [comment]
fixed in https://github.com/tidalcycles/strudel/pull/783
