### ISSUE TITLE
splice isn't cps-aware

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#826]
This shouldn't be gappy:
```js
samples('github:yaxu/clean-breaks')

setcps(0.5)

s("think")
  .splice(8, "0 1 2 3 4 5 6 7")
```

**Comment by daslyfe** [comment]
this might have some crossover with https://github.com/tidalcycles/strudel/issues/821

**Comment by felixroos** [comment]
fixed with https://github.com/tidalcycles/strudel/pull/932
