### ISSUE TITLE
redirect strudel.tidalcycles.org trafic to strudel.cc

### ISSUE THREAD

**Issue by atfornes** [tidalcycles/strudel#829]
After the URL change from strudel.tidalcycles.org to strudel.cc, services that used the previous URL like https://flock.cc stopped working. Console tipically shows a CORS error when this happens.

**Comment by yaxu** [comment]
There is a redirect but I guess that doesn't work for everything, and needs a hard refresh in the browser to trigger due to caching.
https://next.flok.cc/ does work nicely

**Comment by ilesinge** [comment]
In my main browser (Firefox on Linux) I still don't see the redirection, the request is made but points to github servers:

GET https://strudel.tidalcycles.org/workshop/pattern-effects

````HTTP/1.1 200 
accept-ranges: bytes
access-control-allow-origin: *
age: 0
cache-control: max-age=600
content-encoding: gzip
content-length: 8066
content-type: text/html; charset=utf-8
date: Sat, 28 Oct 2023 07:47:54 GMT
etag: W/"653c26d2-a8d3"
expires: Sat, 28 Oct 2023 07:57:54 GMT
last-modified: Fri, 27 Oct 2023 21:08:34 GMT
server: GitHub.com
vary: Accept-Encoding
via: 1.1 varnish
x-cache: MISS
x-cache-hits: 0
x-fastly-request-id: a725f6dc5a599b56851b6f231014955285cfec46
x-firefox-spdy: h2
x-github-request-id: 354A:113C:435880C:4471529:653CBCA8
x-origin-cache: HIT
x-proxy-cache: MISS
x-served-by: cache-par-lfpg1960023-PAR
x-timer: S1698479274.999785,VS0,VE105```

And I see the old server.
The issue does not happen on Chrome on the same laptop, and if I copy the request from firefox console to do it as a curl request in the terminal, I correctly see the 301 redirect from slab.org nginx server.

On my mobile phone, both Chrome and Firefox have the problem.

There seems to be DNS cache problems but it's hard to pinpoint the issue.
Was there a moment when strudel.tidalcycles.org DNS pointed to Github servers ?
How is strudel.cc hosted, I believe it's on Github servers ? Is there a way to tell Github server to redirect requests using the old strudel.tidalcycles.org domain to the new domain ?

**Comment by ilesinge** [comment]
Since strudel can be used to host any kind of JavaScript, I think that would not be a good thing security-wise to do that. Maybe ask the flok server maintainer to update the URL on their side ?

**Comment by yaxu** [comment]
@felixroos Ok done, and that fetch command seems to work now?

@ilesinge Hmm what are the security issues here?

**Comment by ilesinge** [comment]
Actually I misread the proposal 😇 - you can ignore my comment

**Comment by felixroos** [comment]
> @felixroos Ok done, and that fetch command seems to work now?
> 
> @ilesinge Hmm what are the security issues here?

works now! also tested on regular flok and the samples seem to load fine

**Comment by felixroos** [comment]
still not sure why some people will not get redirected from the old to the new domain.. but that should now be less of a problem now that the sample url works. maybe it's some cache issue that'll go away eventually...

**Comment by felixroos** [comment]
> @felixroos I have this problem on both my computers. It doesn't happen in a private window so it's a browser cache issue of some kind. The annoying thing is that strudel still autocompletes to strudel.tidalcycles.org and so I often find myself there. Of course I could spend some seconds solving this by clearing history and cache but haven't got around to that so far.

it's probably the PWA that is still cached.. it might be stuck there now because now new version is found. not sure what to do about that

**Comment by felixroos** [comment]
> It doesn't look like a browser cache issue, since as described I see the request being made and the server is answering with a 200 OK.
> 
> This looks more like a DNS cache issue.
> 
> When the answer is 200 on the old domain, it's GitHub that's answering instead of slab.org as expected.

are there ways to invalidate the DNS cache?
