### ISSUE TITLE
Some relative paths break when site base is not root ("/")

### ISSUE THREAD

**Issue by shiyouganai** [tidalcycles/strudel#832]
Hello,

Recently, I wrote my first strudel pattern and was intrigued by the display possibilities offered by the ["my patterns"](https://github.com/tidalcycles/strudel/tree/main/my-patterns) feature. I forked and deployed strudel on my own TLD but with a base path of `"/strudel"`, and unfortunately a handful of things broke which seem to have the root cause of using:
- Relative `href` paths in `.astro` file HTML
- Relative paths in calls to `samples()` in `prebake.mjs`

These relative paths do not seem to work "intuitively" under the astro framework when the site base is not `"/"` and will pop up with warnings in the development console phrased as:

`[dev] Requests for items in your public folder must also include your base.` (specific file information follows after)

You can see the breakage on the example deployment at https://felixroos.github.io/strudel/swatch/.

I hacked a fix for the immediately noticible broken functionality like drum sample packs and the swatch page, but many of the links in the `/workshop` pages are broken too. I do not know what a good way to fix those would be since working with these web frameworks is outside of my wheelhouse, and the workshop links are written in MDX files.

Here is a link to a diff of my [branch](https://github.com/tidalcycles/strudel/compare/main...shiyouganai:strudel:saved-patterns), and my deployed strudel based on that branch is here: https://shiyouganai.dev/strudel, with a now working swatch page at: https://shiyouganai.dev/strudel/swatch.

I would like to contribute the fix via PR in a more polished way which also addresses the MDX file links in the workshop pages, but I would like to ask for input about how best to go about it since I am very unfamiliar with MDX and how to get variable data like the site base into those links.

**Comment by felixroos** [comment]
thanks for the detailed report! I think I've found a good way to fix all the links in MDX files, for which I've started this PR: https://github.com/tidalcycles/strudel/pull/842 also aiming to fix https://github.com/tidalcycles/strudel/issues/841 . 
The docs are a bit in flux at the moment because we are adding / improving the search. 
If you want to help out, you can open a PR to the branch I've created (slashocalypse) and add your existing fixes there!

**Comment by felixroos** [comment]
with https://github.com/tidalcycles/strudel/pull/842 most of this is now fixed only the font urls are still broken.
For that, I've created this follow up issue: https://github.com/tidalcycles/strudel/issues/847
