### ISSUE TITLE
pnpm t works for version 8.3.1, but fails for newer 8.11.0

### ISSUE THREAD

**Issue by bwagner** [tidalcycles/strudel#833]
`pnpm t` works for version pnpm 8.3.1, but fails for newer pnpm 8.11.0.

**Comment by felixroos** [comment]
that one also gets caught on pnpm 8.11.0 for me

**Comment by felixroos** [comment]
also tried on node v18.18.2 and it also works as expected

**Comment by bwagner** [comment]
Just tried and can confirm. Sorry for all the hubbub I created. No idea why it didn't work before (I'd rebooted in between).
I'll provide a PR with updates to my previous changes related to this.
