### ISSUE TITLE
Double quoted strings and mini notation

### ISSUE THREAD

**Issue by hewIngram** [tidalcycles/strudel#859]
I've been playing with Tidal cycles for a while and discovered Strudel recently - super excited with the possibility of using some other web apis with Strudel to make things.

I love that the repl can handle most JS I throw at it. I got caught up yesterday on the single vs double quote thing - I understand the "use singlequotes and you can write all the Javascript you want" which I totally get *but* I think (do correct me if I'm wrong) this is caused caused purely by the looseness of `isStringWithDoubleQuotes` - or rather the assumption that all double quoted strings are mini notation.

Pulled the repo down and had a little fiddle with expanding this to inspect both the child and parent node so that we can expand it such that we do the mini notation parsing only if it's a `node.type === 'Literal'` and if the parent calling is one of the Studel methods that are expecting mini notation. Is this something you'd want to implement? I'm happy to raise a PR if it would be useful.

I also started poking around at some string concatenation and see some issues with template literals - is this something you've looked at? Appears to possibly be an issue with acorn itself? String concatenation with `+` looks to work as expected which is cool.

Anyway, fab project and I'm really excited to dive into it more.

**Comment by felixroos** [comment]
hey @hewIngram, glad you like the project!

> Pulled the repo down and had a little fiddle with expanding this to inspect both the child and parent node so that we can expand it such that we do the mini notation parsing only if it's a node.type === 'Literal' and if the parent calling is one of the Studel methods that are expecting mini notation. Is this something you'd want to implement? I'm happy to raise a PR if it would be useful.

The problem with that approach is that mini notation might also appear in places where no strudel function is around: https://strudel.cc/?vUTEg5ZAk4Iz

in this example, the double quoted string assigned to the `notes` variable is still treated as mini notation, which is what I'd expect. The fact that you could want to use these patterns in any syntactical situation makes it impossible to interpret when a user might want a string or a pattern, so adding the simple rule of "double quotes = mini notation" resolves any ambiguity + simplifies the transpiler.

> I also started poking around at some string concatenation and see some issues with template literals - is this something you've looked at? Appears to possibly be an issue with acorn itself? String concatenation with + looks to work as expected which is cool.

template literals are also treated as mini notation, to be able to write multiline patterns.

I understand the problem that it's not very ergonomic to only have single quotes to construct strings. If you use strudel as a library outside of the repl, you can choose to just skip the transpile step (strings will be strings) and call the `miniAllStrings` function instead (exported from the /mini package), to to treat any string passed to any strudel function as mini notation.

**Comment by hewIngram** [comment]
> The problem with that approach is that mini notation might also appear in places where no strudel function is around: https://strudel.cc/?vUTEg5ZAk4Iz

This makes sense! The ergonomics of being able to use strings like this as variables feels super important. I guess there is an approach of wrapping all miniNotation strings in a method to parse just them *but* that feels gross and very mush like getting in the way of the user and what they want to do.

Thanks for the info - will have a proper look through some examples and will try to train my lazy JS brain to use single quotes.
