### ISSUE TITLE
MIDI velocity should also be affected by gain?

### ISSUE THREAD

**Issue by totalgee** [tidalcycles/strudel#867]
When I modify the `gain`, it has no effect on notes sent out via `midi`. I would expect gain would modulate (multiply) the velocity, or something like that, the documentation says it does, but maybe it's not implemented for MIDI.

Also -- probably unrelated -- `velocity` seems to not behave well in some cases with patterns, but this may be related to the "hap values"(maybe #507 ?).

> Also, are the default parameter values documented somewhere? (Like gain, velocity, etc.)

**Comment by felixroos** [comment]
sry for late answer, yes gain should be used by the midi output I'd say. gain and velocity are documented here: https://strudel.cc/learn/effects/#dynamics

**Comment by totalgee** [comment]
Yes, but that's my point, they should be multiplied together (`velocity` and `gain`), but `gain` does nothing when sending MIDI from Strudel. Only `velocity` is used, but I think `gain` should probably also be applied as a multiplier, to be more consistent to what happens with non-MIDI samples and synths...

**Comment by felixroos** [comment]
fixed in https://github.com/tidalcycles/strudel/pull/974

**Comment by totalgee** [comment]
Great, thank you!
