### ISSUE TITLE
slowcat should support arrays

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#87]
`slowcat(0, [1, 2])` currently does not work. It would be handy if it worked analogous to `"<0 [1 2]>"`

**Comment by yaxu** [comment]
I noticed this too earlier, fix incoming..

**Comment by yaxu** [comment]
I'm a bit nervous about this though.. What if you want to make a pattern of lists, like chords? Could wrap them in `pure` but that would be a bit annoying

**Comment by felixroos** [comment]
wouldnt you do that with stack? the same could be said about sequence.. its also not really clear what the difference between sequence and cat is. do we need slowsequence?

**Comment by yaxu** [comment]
A pattern of lists is a bit different from a pattern with events that coincide. Although they're not used in tidal the desire to have them has come up occasionally. I'm fine with this as the default behaviour though and looking for workarounds later if necessary
Yes true we should merge cat and sequence now. Probably we just drop the latter.

**Comment by felixroos** [comment]
https://tidalcycles.org/docs/patternlib/tour/concatenation/#cat in tidal cat is slowcat, while in strudel, its fastcat..

**Comment by yaxu** [comment]
Hmm. Which do you prefer? I guess slowcat is nice for composing patterns together, fastcat is nice as an alternative to mininotation

**Comment by yaxu** [comment]
So maybe cat should be a slowcat and sequence should be a fastcat

**Comment by felixroos** [comment]
ok! maybe add seq as a shortcut too? we would also need to refactor cat usage in tunes.mjs

**Comment by yaxu** [comment]
Yes to `seq`.

I'm just heading out now but just committed `sequence` -> `fastcat` and `cat` -> `slowcat`. It breaks an eval.mjs test too.

**Comment by felixroos** [comment]
just migrated all the tunes + tutorial snippets to new cat behaviour
