### ISSUE TITLE
scale function not working as expected

### ISSUE THREAD

**Issue by ShawnToubeau** [tidalcycles/strudel#883]
Hi! 

I think I found a bug with the `.scale()` function? It's producing a different sound than it did for me yesterday.

Here's a melody running in a local strudel instance (commit `4871abbd713cbe1aec69a0858f45252fed58f205` from a few days ago).

https://github.com/tidalcycles/strudel/assets/22332636/904d7fa3-30b0-44a2-aefc-94d2db9bbc1e

And here's the same melody running in a refreshed window at strudel.cc ([sketch link](https://strudel.cc/?UTqd1_9W8i9O)). You'll see that the sound doesn't change when I add or remove the scale unlike the other video.

https://github.com/tidalcycles/strudel/assets/22332636/25ecb05a-5c71-473b-a67a-5de42720b287

**Comment by felixroos** [comment]
hey @ShawnToubeau !

this probably came from yesterdays change in the scale function: https://github.com/tidalcycles/strudel/pull/880/files#diff-494fcbad55a1e686f45e8d0211c7dfa10a80e8b0325ad8f09964d568eaeeced2R164-R198

I wasn't aware that that change would affect any existing code out there, as all tests were passing.

So this is technically a breaking change, although `n` is intended to set the scale step and not a note.. to get a note, you need to use the `note` function:


```js
note("f# b a")
.s("gm_bassoon:3")
```

to get scale notes, you can use `n` with numbers:

```js
n("0 1 2")
.scale("F#:minor")
.s("gm_bassoon:3")
```

I would be interested in why that old behavior would be useful to preserve / why you need that specific behavior of `n`?

**Comment by ShawnToubeau** [comment]
Got it! Thank you for clarification and I was able to update my code accordingly!

I don't have any reason for using the old behavior so I can go ahead and close this 😁
