### ISSUE TITLE
append is redundant

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#89]
Because strudel has varargs, `cat` can do everything that `append` does. Similarly `stack` does everything that `overlay` does in tidal.

Do we make append and overlay aliases of cat and stack? Or just not have them in strudel at all?

**Comment by felixroos** [comment]
Maybe just remove them? I guess they are not that frequently used by tidal users, so it might be ok?

**Comment by yaxu** [comment]
Ok agreed, I'll remove `append`. `overlay` isn't implemented yet anyway.
