### ISSUE TITLE
Incorrect samples URL in some Strudel examples using freesound.org

### ISSUE THREAD

**Issue by pierredewilde** [tidalcycles/strudel#914]
In some Strudel examples using freesound.org for samples like `Random bells`, `Wavy kalimba`, `Bridge is over`, URL is incorrect.

`https://freesound.org/data/previews/...` => `https://cdn.freesound.org/previews/...`

**Comment by felixroos** [comment]
thanks, there is already this issue: https://github.com/tidalcycles/strudel/issues/875 If you want, you can send a PR for that
