### ISSUE TITLE
transpile label expressions to `p` calls

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#990]
label expressions could be used to set the key of the pattern:

```js
p1: s("bd*4")

p2: note("c e g b")
```

could be made equivalent to:

```js
s("bd*4").p('p1')
note("c e g b").p('p2')
```

label expressions are a niche js syntax that is very much unused, so perfect for overloading.
This benefits readability, especially in combination with inline widgets:

before:

<img width="552" alt="image" src="https://github.com/tidalcycles/strudel/assets/12023032/c3bcbe31-889b-4cd2-a679-0827ce3f5dd8">

after:

<img width="539" alt="image" src="https://github.com/tidalcycles/strudel/assets/12023032/d78f467b-a83d-4382-ba7b-58c1610efd29">

**Comment by strickinato** [comment]
I've been exploring using strudel with coffeescript. 

I have a preference for it's syntax, I think it's nice not to mess around with the parentheses while code.

eg.

```coffeescript
n "0 3 <5 7> 3"
  .scale "c:minor"
  .sound "piano"
  .jux rev

s "bd <sd cp>"
```

Interestingly, coffeescript doesn't support labelled expressions! niche indeed!

Which means that the above has to be written as:

```coffeescript
n "0 3 <5 7> 3"
  .scale "c:minor"
  .sound "piano"
  .jux rev
  .p1

s "bd <sd cp>"
  .p2
```

Not trying to push an agenda, just putting this note here for posterity. <3

**Comment by felixroos** [comment]
> I've been exploring using strudel with coffeescript.
> 
> I have a preference for it's syntax, I think it's nice not to mess around with the parentheses while code.
> 
> eg.
> 
> n "0 3 <5 7> 3"
>   .scale "c:minor"
>   .sound "piano"
>   .jux rev
> 
> s "bd <sd cp>"
> 
> Interestingly, coffeescript doesn't support labelled expressions! niche indeed!
> 
> Which means that the above has to be written as:
> 
> n "0 3 <5 7> 3"
>   .scale "c:minor"
>   .sound "piano"
>   .jux rev
>   .p1
> 
> s "bd <sd cp>"
>   .p2
> 
> Not trying to push an agenda, just putting this note here for posterity - and calling out that this decision has an extremely mild negative impact on strudel-as-a-transpilation-target 😄
> 
> Maybe this will matter one day, maybe not 🤷
> 
> Thanks [@felixroos](https://github.com/felixroos) for amazing software 🎉

hey @strickinato I've never really messed with coffeescript but that syntax looks neat! there is also the geenric `p` function which accepts any number or string:

```js
s "bd" . p 0

s "- cp" . p 1
```

> and calling out that this decision has an extremely mild negative impact on strudel-as-a-transpilation-target

i'm not sure if i understand correctly, but the labeled expressions are not needed to get this functionality, as you can transpile to p function calls directly.

**Comment by strickinato** [comment]
> i'm not sure if i understand correctly, but the labeled expressions are not needed to get this functionality, as you can transpile to p function calls directly.

You understood perfectly, but I wrote that late at night it was kind of a mistaken point 😄. 

The syntax that this issue represents (using labelled expressions to get that top level definition for the channel) is really nice, and I was a little bummed that in my coffeescript exploration, I can't quite have it.

Once again - thanks for the amazing project
